### ISSUE TITLE
verify authorized unless Devise controller

### ISSUE THREAD

**Issue by heratyian** [appdev-lessons/pundit-authorization#1]
Not able to edit user registration after adding verify_authorized. Need to explicitly allow devise controllers.

```
after_action :verify_authorized, unless: :devise_controller?
after_action :verify_policy_scoped, only: :index, unless: :devise_controller?
```

cc: @rsfarzo @fidel-techprep

**Comment by bpurinton** [comment]
Thanks! Updated on this commit: https://github.com/appdev-lessons/pundit-authorization/commit/d94580a7aa7231b7a3c6eb6e5ad39d365b40b3c3
