### ISSUE TITLE
Issue with authorization for feed & users controller

### ISSUE THREAD

**Issue by armstrca** [appdev-lessons/pundit-authorization#2]
After implementing the fix mentioned in the other issue here, ran into a UsersController error when trying to access the root url, which is `users#feed`. 

This was a result of having the following line in `application_controller.rb` as suggested in the Learn lesson:
```
# app/controllers/application_controller.rb
after_action :verify_authorized, except: :index
after_action :verify_policy_scoped, only: :index
```
I had a `UserPolicy` inheriting from `ApplicationPolicy`, but since neither the lesson nor `ApplicationPolicy` had a way to handle `feed`, had to update `UserPolicy` as such:

```
# app/policies/user_policy.rb

class UserPolicy < ApplicationPolicy
  attr_reader :current_user, :user

  def initialize(current_user, user)
    @current_user = current_user
    @user = user
  end

  # def feed?
  #   true
  # end

  def show?
    user == current_user ||
     !user.private? || 
     user.followers.include?(current_user)
  end
end
```
Thanks to Ian Heraty for helping me with this.
Might be helpful to other students to have something addressing this issue in the Learn lesson.

**Comment by bpurinton** [comment]
Did you mean to comment out the code in your post? You have:

```ruby
  # def feed?
  #   true
  # end
```

But I'm guessing you meant:

```ruby
  def feed?
    true
  end
```

Just want to be sure I follow!

**Comment by armstrca** [comment]
Yes, that's correct

**Comment by bpurinton** [comment]
Thanks! [I've updated the lesson to note this](https://learn.firstdraft.com/lessons/202-pundit-authorization#:~:text=If%20you%20are,feed%3F%0A%20%20true%0Aend)
